### PR TITLE
Create uploadFile api, fix issue #28

### PR DESCRIPTION
**Pull request by stonyz**
just add uploadFile api, and also tested. the test scripts,

```
channelId='sxe84mdeibd8xyu5i1fx7eyskw'
file = '/Users/stonyz/Desktop/aaa.png'
client.on 'channelsLoaded', () -> 
    client.uploadFile channelId, file , (resp) ->
        console.log JSON.stringify(resp)
        file_id = resp.file_infos[0].id;
        client.customMessage {message:'Test by Stony',file_ids:[file_id]}, channelId
```

### CODE REVIEW

**Comment by loafoe** [comment]
@stonyz can  you please your fork to latest `master`? Great work!!

**Comment by stonyz** [comment]
Yes, I have merged your latest change, you can merge directly.

**Comment by loafoe** [comment]
@stonyz sorry for letting this linger, is it still relevant for you to port it to the new `js` based `5.0` release? I can take stab at it otherwise, but will not be right away.

**Comment by loafoe** [comment]
@stonyz closing this for now

**Pull request closed without merging**
