### PR TITLE
Add support for sending a cmd to a spez. channel

### PR DESCRIPTION
**Pull request by mlmnetcologne**
With this funktion, e. g. the hubot can send a command like "/echo hioh" to a channel.
in the coustom hubot script (.coffee):
msg.robot.adapter.client.postCommand('the_channel_id','/echo hioh');

In the future it would be nice, if 'the_channel_id' could either be the channel_id or the name of the channel. ('~channel_name')

### CODE REVIEW

**Comment by mlmnetcologne** [comment]
https://github.com/loafoe/mattermost-client/pull/118/checks?check_run_id=415263881#step:5:36 this is not an error! The comma would result in one. The rest errors are from different lines.

**Comment by DanielRuf** [comment]
Hi @mlmnetcologne,

We have a new repo at https://github.com/bitexpert/mattermost-client-node with many improvements.

Regarding the output from CI: GHA triggers checks only on touched / changed files. And these are mostly warnings.

We enforce specific rules like trailing comma.

**Comment by mlmnetcologne** [comment]
https://github.com/bitexpert/mattermost-client-node 
So this is, what is installed, when I install hubot?

**Comment by DanielRuf** [comment]
> when I install hubot-matteruser

No, https://www.npmjs.com/package/hubot-matteruser still uses the other one. You would have to fork this too. We just forked the client.

**Comment by DanielRuf** [comment]
I have no access to the npm repos or any admin access as previously requested. Only @loafoe can do the needed steps.

**Comment by mlmnetcologne** [comment]
@DanielRuf can you reopen this pull request?

**Comment by DanielRuf** [comment]
Sure but this repo is broken =)
See the CI and commits which were merged but shouldn't be merged. I reverted some but others merged other changes which break things.

**Comment by mlmnetcologne** [comment]
Okay, thank you.

**Comment by mlmnetcologne** [comment]
Ok I do it again

**Comment by DanielRuf** [comment]
> Sure but this repo is broken

Not your PR, it will not magically fix it =)

**Pull request closed without merging**
